dependencies {
    implementation "io.github.qishr:cascara-common:1.1.12"
    implementation "io.github.qishr:cascara-common-io:0.9.0"
    implementation "io.github.qishr:cascara-format-vsix:0.1.0"
    implementation "io.github.qishr:cascara-lang-json:0.9.0"
    implementation "io.github.qishr:cascara-lang-xml:0.9.0"
    implementation "io.github.qishr:cascara-lang-yaml:0.9.0"
    implementation "io.github.qishr:cascara-schema:0.9.0"
    implementation "io.github.qishr:cascara-ui:0.9.0"
}